### ISSUE TITLE
Cannot compile master

### ISSUE THREAD

**Issue by racerxdl** [ktechlab/ktechlab#44]
I'm trying to compile the master branch here, but looks like one of the files are not generated:

```
In file included from /media/ELTN/Works/ktechlab/src/ktechlab.cpp:18:0:
/media/ELTN/Works/ktechlab/src/gui/contexthelp.h:14:10: fatal error: ui_contexthelpwidget.h: Arquivo ou diretório inexistente
 #include <ui_contexthelpwidget.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
```

Tried to find references about it, but the only reference is on `build-simple.sh` which also does not work.

Is there anything I'm missing? 

EDIT: Looks like the commit 8b0ccf110fa3b4efbb1e2719d103d8eb16865e1f works nice.

**Comment by zoltanp** [comment]
For reference:

The script `build-simple.sh` should work. Using purely cmake + make sometimes generates the issue 
you have cited below; it's something related to KDE4 cmake files, and I don't really want to spend effort fixing those, instead I want to port to KF5 and Qt5.

As I understand,  `build-simple.sh` works for you (after an update, I assume), so I'm closing this issue. If not, feel free to reopen, or open other issue.

Have fun with KTechlab!
