### ISSUE TITLE
ecsignallamp.cpp:68: sequence point error ?

### ISSUE THREAD

**Issue by dcb314** [ktechlab/ktechlab#46]
ecsignallamp.cpp:68:4: warning: operation on '((ECSignalLamp*)this)->ECSignalLamp::advanceSinceUpdate' may be undefine
d [-Wsequence-point]

Source code is

        avgPower = fabs(avgPower * advanceSinceUpdate +
                        (voltage * voltage / RESISTANCE)) /
                        ++advanceSinceUpdate;

You can't increment something and read from it between sequence points.
Suggest code rework.

**Comment by zoltanp** [comment]
Which version have you compiled? The latest `master` branch (for example from this repository) is already fixed:

```
	avgPower = fabs(avgPower * advanceSinceUpdate +
			(voltage * voltage / RESISTANCE)) /
			advanceSinceUpdate;
++advanceSinceUpdate;
```

https://github.com/ktechlab/ktechlab/blob/master/src/electronics/components/ecsignallamp.cpp#L69

**Comment by UfoDriver** [comment]
@zoltanp can you please explain what is going on in those lines?

Basically I have a problem. If I apply some voltage on the lamp and then remove it, the lamp remains lit. Some debug messages showed me that `avgPower` grows constantly when we apply voltage and remains on the same level without it. I believe that the code is broken but have no internals knowledge of KTechLab to fix it.

**Comment by zoltanp** [comment]
@UfoDriver I confirm, the issue with the signal lamp still applies.

The code tries to calculate a rolling average of power dissipated on the signal lamp. Unfortunately this calculation is wrong (just verify the units of measurement, avgPower should be power (`watts`) , while avgPower * advanceSinceUpdate is `watts * seconds` and ` voltage * voltage / RESISTANCE ` is watts, which is correct, but dividing it by time ( advanceSinceUpdate ) is not ... Everywhere should be watts, not some strange units..


Cross-linking with KDE bugzilla:

https://bugs.kde.org/show_bug.cgi?id=455968

**Comment by zoltanp** [comment]
@UfoDriver Fixed in git master, apparently this simple fix works:

https://invent.kde.org/sdk/ktechlab/-/commit/680651eb813cecb6691bb539b3e144955e7af4c4
