### ISSUE TITLE
gspimprocessor.cpp compiling error

### ISSUE THREAD

**Issue by balebanov** [ktechlab/ktechlab#55]
Good evening! 

I've got an error after "cmake" command. build-simple.sh runned successfully. Here is my error:

UPD: Uploaded to PasteBin:
https://pastebin.com/iWigvB01

**Comment by Petross404** [comment]
Can you put inside code tags so it's easier for the eyes?

Thanks.

**Comment by balebanov** [comment]
> Can you put inside code tags so it's easier for the eyes?
> 
> Thanks.

Sorry for that, I wonder why inserting code function doesn't work for me. I've put that to PasteBin: https://pastebin.com/iWigvB01
Thanks

**Comment by Petross404** [comment]
Re-create the build directory (or erase all it's contents) and try to run and give us the following:

```bash
cd pat/to/build
rm -rv ./*
cmake .. && make -j1
```

So we can see what cmake does (not that this is it's fault) and of course run make with -j1 so it can stop immediately after the very first error. I can't quite address where the error happened in your previous log.

**Comment by balebanov** [comment]
https://pastebin.com/7zr3GH7a
Here it is. I skipped pasting there generation of build files, it was successful

**Comment by balebanov** [comment]
What does "W" mean? Should I do something with source code files?

`/home/user/Загрузки/Programs/ktechlab/src/electronics/gpsimprocessor.cpp:761:56: error: ‘class pic_processor’ has no member named ‘W’
  RegisterInfo * info = new RegisterInfo( picProcessor->W );`

**Comment by Petross404** [comment]
Indeed 
```bash
.../Programs/ktechlab/src/electronics/gpsimprocessor.cpp:761:56: 
error: ‘class pic_processor’ has no member named ‘W’
RegisterInfo * info = new RegisterInfo( picProcessor->W );
                                                        ^
```

And 
```cpp
#if defined(HAVE_GPSIM_0_26)
	RegisterInfo * info = new RegisterInfo( picProcessor->Wreg ); // is tihs correct for "W" member? TODO
#else
	RegisterInfo * info = new RegisterInfo( picProcessor->W );
#endif
``` 
[informs](https://github.com/ktechlab/ktechlab/blob/master/src/electronics/gpsimprocessor.cpp#L758) us that one should use GPSIM 0.26. Back at the [CMakeLists.txt](https://github.com/ktechlab/ktechlab/blob/master/CMakeLists.txt#L58) I see that GSPIM is indeed required but I can't see any version required.

Please post your GSPIM version and how you installed it in case it's older than 0.26.

**Comment by balebanov** [comment]
@Petross404 I've remove and install again GPSIM 0.31.0 version. I used an instruction in official site of GPSIM: http://gpsim.sourceforge.net/#install
I haven't got any error during its installation. Then I run again in ktechlab directory: 
`cmake .. && make -j1`
And got same error:
`/home/user/Загрузки/Programs/ktechlab/src/electronics/gpsimprocessor.cpp:761:56: error: ‘class pic_processor’ has no member named ‘W’
  RegisterInfo * info = new RegisterInfo( picProcessor->W );`

**Comment by Petross404** [comment]
It seems you installed it without a package manager but anyway. Also as a side note, it's best to rm your build directory before retrying after a failed compilation.

You have install version 0.31 and yet `HAVE_GPSIM_0_26` is undefined? Why it doesn't compile 	`RegisterInfo * info = new RegisterInfo( picProcessor->Wreg );` instead?

If you know a little about cmake you could use `message()` command to ouput the value of `HAVE_GPSIM_0_26` to debug the CMakeLists.txt. It's late here, so if you find it difficult ping me tomorrow.

Or you can wait the author to answer as I don't have other ideas. Sorry.

All the best,
Petros

**Comment by balebanov** [comment]
I've just noticed this part of output of `cmake ..`:

`-- Performing Test HAVE_GPSIM_0_26`
`-- Performing Test HAVE_GPSIM_0_26 - Failed`
`-- Found GPSim: /usr/local/lib/libgpsim.so  `

So I don't know why this test returned **Failed**. I found GPSIM in my package manager and installed it too. About your question 

> Where is gpsim-0.31 installed?

I can tell you that just dowloaded .tar.gz file from their site, unpacked it, compiled and runned `sudo make install`, so I've found GPSIM files in `/usr/local/include/gpsim` (C++ header files) and `/usr/local/lib` (.so libraries).

Regards.

**Comment by Petross404** [comment]
CMake output is often useful despite being succesful ;) What is your distro and what version of GPSIM is the greatest? Also can you uninstall the manually compiled GPSIM?

> I've just noticed this part of output of cmake ..:-- Performing Test HAVE_GPSIM_0_26-- Performing Test HAVE_GPSIM_0_26 - Failed-- Found GPSim: /usr/local/lib/libgpsim.so
--

Let me look where this variable is defined in cmakelists.txt. Perphaps `HAVE_GPSIM_0_26` mean only this, having 0.26 version, not a greater one.

**Comment by balebanov** [comment]
Petros, I use LM 19.1. Just uninstalled GPSIM which was compiled: `sudo make uninstall`. I found gpsim-0.26.1 (there's no 0.26.0), should I install it instead of 0.31 which installed by package manager?

**Comment by adrian-the-git** [comment]
gpsim renamed `W` to `Wreg` sometime during the 0.26.x releases ([commit 2213](https://sourceforge.net/p/gpsim/code/2213/tree//trunk/ChangeLog)) and the cmake module `FindGPSim.cmake` does the right thing by attempting to compile code referencing `pic_processor->Wreg` and setting `HAVE_GPSIM_0_26` when that compilation succeeds.

The problem arises because a gpsim header called `breakpoints.h` tries to `#include "../config.h"`, which usually fails, preventing `HAVE_GPSIM_0_26` from being set (and presumably, faking this flag would be insufficient because the `../config.h` file is still missing). This bug has shown up [elsewhere](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939338).

Until gpsim fixes their headers, you can probably fix this with a kludge like:

```
--- a/cmake/modules/FindGPSim.cmake
+++ b/cmake/modules/FindGPSim.cmake
@@ -46,7 +46,12 @@ find_path(GPSim_INCLUDE_DIR
 find_library(GPSim_LIBRARY NAMES gpsim)
 
 if (GPSim_INCLUDE_DIR AND GPSim_LIBRARY AND GLib_FOUND)
-    set(GPSim_INCLUDE_DIRS ${GPSim_INCLUDE_DIR} ${GLib_INCLUDE_DIRS})
+    # Make a fake config.h to satisfy GPSim's broken headers
+    set(GPSim_KLUDGE_DIR "${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/kludge/include")
+    file(MAKE_DIRECTORY "${GPSim_KLUDGE_DIR}")
+    file(TOUCH "${GPSim_KLUDGE_DIR}/../config.h")
+
+    set(GPSim_INCLUDE_DIRS ${GPSim_INCLUDE_DIR} ${GLib_INCLUDE_DIRS} ${GPSim_KLUDGE_DIR})
     set(GPSim_LIBRARIES ${GPSim_LIBRARY} ${GLib_LIBRARY})
```

...although someone with better knowledge of cmake might know of better path variables to use. @balebanov looks like you've moved on, but if you're still interested you can likely build ktechlab with this fix.

**Comment by zoltanp** [comment]
@adrian-the-git Thanks for the investigation! If this patch fixes the issue, then I will add it as a commit to the repository.

Note to self:
1. There is another open issue related to FreeBSD, might be the same:
https://github.com/ktechlab/ktechlab/issues/57

2. To notify gpsim developers about (1) broken header issue and (2) discuss about API compatibility, and ask for exposing version information their installed headers

**Comment by zoltanp** [comment]
Pushed a fix for this issue into git master. Feel free to test.

Remaining TODO for me (or for a volunteer):

* To notify gpsim developers about (1) broken header issue and (2) discuss about API compatibility, and ask for exposing version information in their installed headers

**Comment by zoltanp** [comment]
Broken header issue:
https://sourceforge.net/p/gpsim/bugs/253/

Request for version information:
https://sourceforge.net/p/gpsim/feature-requests/63/

Closing ticket as it is fixed and relevant issues reported upstream. If it is not fixed, feel free to reopen.
